### ISSUE TITLE
Switch job title in registration to a dropdown

### ISSUE THREAD

**Issue by jayzes** [denverstartupweek/dsw-site#111]
Accounting & Finance 
Contract & Freelance
Customer Service/Success
Data/Analytics
Design
Developer/Engineer
Founder / Executive
Government
Health Care
Hospitality
Information Technology
Manufacturing
Non-profit
Operations
Product
Recruiting & Human Resources
Sales & Marketing
Writing & Content
Other

**Comment by marikaross** [comment]
Hello!  We're a group of students finishing up at Turing in the front-end program.  We're hoping to help out with this issue. As of now, nobody is assigned to it, but if there’s already a solution in progress we're happy to try helping out elsewhere. Thanks!

**Comment by jayzes** [comment]
@marikaross absolutely, go for it!
