### ISSUE TITLE
Weird box behind header on the homepage

### ISSUE THREAD

**Issue by jayzes** [denverstartupweek/dsw-site#152]
@guiceworks sees it in both Chrome and Safari (screenshot attached). I can't seem to replicate.

![dsw_gt_qa_1](https://user-images.githubusercontent.com/22783/30523351-25302716-9b9d-11e7-9ff3-09bf9b6434dd.png)

**Comment by bluesbroz** [comment]
Maybe it's because `overflow-x` is set to `scroll` for `.inner-modal-container`? Try to set it to `auto`.
