### ISSUE TITLE
News & press page should show an excerpt for the article/release

### ISSUE THREAD

**Issue by ryefinegan** [denverstartupweek/dsw-site#218]
As discussed, can we structure this so that it shows a few lines of the article?  Kate uses the following example when talking about it: http://www.charlottecentercity.org/category/mediapr/ 

Curious what you think is feasible.  It would be great if we can make this editable for me and others, similar to the Homepage CTAs / Sponsorship page.

**Comment by jayzes** [comment]
For sure -  let me see if I can use a different style treatment for that section to get the excerpt in there.

They are currently editable in the admin as well - https://www.denverstartupweek.org/admin/newsroom_items. I'll be sure to add the excerpt field in there too.
