### ISSUE TITLE
Users should be able to upload a profile photo for their accounts

### ISSUE THREAD

**Issue by jayzes** [denverstartupweek/dsw-site#226]
We can use the account edit page for this.

Might be good to add some variety of client-side validation too: https://stackoverflow.com/questions/3717793/javascript-file-upload-size-validation.

**Comment by IlinDmitry** [comment]
This issue still persists?

**Comment by jayzes** [comment]
@IlinDmitry correct - it hasn't been implemented yet. We're using Carrierwave already for uploads/attachments, so I'd rather continue to use that than incorporate Paperclip alongside that. There's already an avatar uploader created and mounted to the user model (https://github.com/denverstartupweek/dsw-site/blob/master/app/models/user.rb#L31), so I think we just need to expose that in the signup/edit forms (https://github.com/denverstartupweek/dsw-site/blob/master/app/views/users/registrations/edit.html.slim and https://github.com/denverstartupweek/dsw-site/blob/master/app/views/users/registrations/new.html.slim) and incorporate that into the test suite.
