### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by jayzes** [denverstartupweek/dsw-site#236]
@marlabrizel has a template to use, I think.

Some interesting stuff here too: https://wearemovingforward.github.io/

Code of conduct needs to live in the following places:
- Site footer partial - accessible from every page
- Mandatory "I have read and agree" checkbox on CFP submission page with link out to COC
- Main nav

**Comment by marlabrizel** [comment]
@jayzes do we want to do any checking to ensure that people have actually visited the COC before submitting a session (beyond just checkign the box saying they have) or is that overkill?

**Comment by jayzes** [comment]
Hmm, that's an interesting idea. My initial inclination is that it's overkill, though I could be convinced otherwise if you feel strongly.

**Comment by jayzes** [comment]
Also - I don't know that it should be in the main nav since space is somewhat constrained there. Seems like it could live under the "Attendees" section in addition to the footer though?
