### ISSUE TITLE
Fix display bug with "+" in FAQ sections

### ISSUE THREAD

**Issue by jayzes** [denverstartupweek/dsw-site#244]
They should be on the same line as the title.

It's related to a margin-bottom on h6 elements that I added sometime last year. Need to make the selector more specific.

**Comment by mmdberg** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!
