### ISSUE TITLE
"Selection" page should link to previous years' schedules

### ISSUE THREAD

**Issue by jayzes** [denverstartupweek/dsw-site#253]
This page: https://www.denverstartupweek.org/program/selection

We should probably do the same for the "previous program" page as well.

**Comment by GabrielAfflitto** [comment]
@jayzes I believe I have solved the issue, but I still have about 39 tests failing, I'm not sure if i have setup the environment correctly. I have followed all the instructions on the Readme.

**Comment by jayzes** [comment]
@GabrielAfflitto what kind of errors are you seeing? If it's any easier, you can open a pull request with a Travis CI run that shows test failures.
