### ISSUE TITLE
Venue picker fixes

### ISSUE THREAD

**Issue by jayzes** [denverstartupweek/dsw-site#401]
- [x] When we assigned a session, it does not change the Venue in the Session Edit page. That venue selection remained black, even though it showed on the venue availability page.
- [x] When we created a venue, it did not show up in My Dashboard. Nor did an assigned session show up.
- [x] On the Venue Selector Page (from the Session View page), it shows all venue availabilities, not sure for the slotted time. Can it just show those that are available during that time window?
- [x] We can send over updated text for the Bacon Ilipsum on the create a venue page
- [x] The Availability Form Date/Time Grid is super hard to tell what is going on. Can we make that easier to understand? Can we add dates to the days of the week? Can we also add a "select all" button? (edited)

**Comment by ryefinegan** [comment]
Denver Startup Week relies on the generosity of venue hosts throughout our center city to provide space for sessions and events. Thank you for welcoming the Denver Startup Week (DSW) community into your space!

As a venue host, you will generously provide space for Denver Startup Week session organizers to put on their event during the week. Most Denver Startup Week sessions are in need a venue for their event, and by providing a space for those sessions to take place, you are playing a critical role to support this entirely free community event.  

For a full overview of expectations and the venue hosting process, please review our Venue Host Handbook here: https://docs.google.com/document/d/1ZlBPLnKJXRQDzJ8cCUNUum5VChHeAeCEiDXs8EUq6KY/edit#

Please complete the form below to provide information about your venue and availability to host. 

Also, please fill out separate forms for each space that will be available for sessions during Denver Startup Week (i.e. if you have two event spaces in your venue, please fill out separate forms for each).

**Comment by jayzes** [comment]
@ryefinegan i've fixed two of these pretty readily (1/4 in the list above). I'll look into 2/5 next. For 3 - it's going to be a bit difficult to match time slots exactly (mostly because we let track chairs pick arbitrary time slots for sessions vs. putting them in the same windows that we offer venues). That said, I've started out by showing both availabilities for the current day, and all availabilities, in separate panes, as a way to see that information more contextually. I can walk you through that when you're back and see if that helps?

**Comment by ryefinegan** [comment]
The approach that shows current day and all availabilities sounds great. The problem we are hoping to tackle is that a certain time availability goes away if a session is assigned during that time. Would it be possible to show that a session is assigned to a allotted availability / time slot when we are viewing availability for a given session? Could that be aligned based upon the check boxes that the venue selects in the day/time grid when they give us their availability?

**Comment by jayzes** [comment]
@ryefinegan going to close this one out as i think they're all addressed for now.
