### ISSUE TITLE
Publishings textacular issues

### ISSUE THREAD

**Issue by scpaye506** [denverstartupweek/dsw-site#513]
@jayzes i'm getting a `ERROR: subquery has too many columns` and it seems like it's because the `textacular` gem results from a `fulltext_search` do not really respect the ActiveRecord model anymore, so things like `.count` and `.select(:id)` don't work. In this instance `.select(:id)` just returns the full ActiveRecord result, not just the results with only the id column selected. Which is causing the subquery has too many columns error since we are passing an object with more than the id column in the where statement further down.

The easiest approach i've found is to just turn it into an array and then pluck out the id column. Not sure exactly of the performance consequences.

Any other approach you'd like to take with this?

_Originally posted by @scpaye506 in https://github.com/denverstartupweek/dsw-site/pull/507_

**Comment by jayzes** [comment]
One other thing I just noticed on this front - the `/articles` page on preview is taking a long time to load because the trivial case where no criteria are specified results in all submission IDs being loaded in. Ging to look at that too.

**Comment by scpaye506** [comment]
> One other thing I just noticed on this front - the `/articles` page on preview is taking a long time to load because the trivial case where no criteria are specified results in all submission IDs being loaded in. Ging to look at that too.

@jayzes adding `where.not(publishing: nil)` should help with that quite a bit. I'll do a PR for it
