### ISSUE TITLE
Staging S3 bucket permissions

### ISSUE THREAD

**Issue by scpaye506** [denverstartupweek/dsw-site#578]
looks like track images uploaded in staging are getting 403 errors when trying to view them

can see the error in the console on this page

https://denver-startup-week-stage.herokuapp.com/program/tracks

```
tracks:2 GET https://dsw-staging-uploads.s3.amazonaws.com/uploads/track/header_image/content_card_CamNewton.jpg 403 (Forbidden)
```

Looks like it might be happening on sometimes on the preview site as well

**Comment by jayzes** [comment]
Checking this out now

**Comment by jayzes** [comment]
Weirdly, somehow the ID is getting lost off of the image URL:

- The request is going to https://dsw-staging-uploads.s3.amazonaws.com/uploads/track/header_image/content_card_CamNewton.jpg
- The actual image lives at https://dsw-staging-uploads.s3.amazonaws.com/uploads/track/header_image/3/content_card_CamNewton.jpg

Looking into reasons why that might be happening.
