### ISSUE TITLE
Compress Card Images

### ISSUE THREAD

**Issue by scpaye506** [denverstartupweek/dsw-site#602]
Getting mediocre page speed reviews on [Google PageSpeed Insights ](https://developers.google.com/speed/pagespeed/insights/) for image heavy pages (pages with lots of cards with images)

[tracks page](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.denverstartupweek.org%2Fprogram%2Ftracks)

[home page](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.denverstartupweek.org%2F)

[articles page](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.denverstartupweek.org%2Farticles)

Compressing the card images by downgrading the quality during the upload processing should help with this. I'm not exactly sure the best number so you might need to play with that.

https://github.com/carrierwaveuploader/carrierwave/wiki/How-to%3A-Specify-the-image-quality

**Comment by jayzes** [comment]
Good call - I'll add something to carrierwave for this
