### ISSUE TITLE
As someone with resources to give, I should be able to submit resources that I want to publicize

### ISSUE THREAD

**Issue by jayzes** [denverstartupweek/dsw-site#776]
Modeled on our existing CFP/article flows, this should be a form that goes someplace in the admin for review and dissemination.

https://www.denverstartupweek.org/articles/new

Need to determine what information is collected. Definitely a user account needed. To start:
- Name
- Image
- Company Name
- Description
- Contact information (optional)
- Website
- Timeframe / expiration date

Should probably kick out a notification e-mail to info@denverstartupweek.org too.

**Comment by jmkoni** [comment]
I have to roll off this project, so reassign if needed!
