### ISSUE TITLE
I should be able to edit resources that I have submitted

### ISSUE THREAD

**Issue by jayzes** [denverstartupweek/dsw-site#803]
Using the same form, etc.

**Comment by jmkoni** [comment]
This is actually partially done as part of #776. However, we still need to determine how we want to display the resources.

**Comment by jmkoni** [comment]
Here's the PR that *mostly* completes this: https://github.com/denverstartupweek/dsw-site/pull/810

There's just not a link to edit anywhere. But if that's added, this will be done.
