### ISSUE TITLE
Update the about page copy to reflect 2019 attendance numbers

### ISSUE THREAD

**Issue by jayzes** [denverstartupweek/dsw-site#874]
https://www.denverstartupweek.org/about

<img width="689" alt="Screen Shot 2020-08-05 at 3 46 09 PM" src="https://user-images.githubusercontent.com/22783/89467491-e3e51800-d732-11ea-966d-32be3e84baaa.png">

**Comment by jayzes** [comment]
Looks like the numbers for 2019 were 20,000 attendees and 359 programs (per https://www.denverstartupweek.org/admin?order=id_desc&q%5Bstate_eq%5D=venue_confirmed&q%5Byear_eq%5D=2019&scope=previous_years)

**Comment by Jessiewithani** [comment]
This issue has been resolved, and is merged into master now.
