### ISSUE TITLE
Remove "Clusters" dropdown from articles page

### ISSUE THREAD

**Issue by jayzes** [denverstartupweek/dsw-site#885]
This page: https://www.denverstartupweek.org/articles

And this dropdown:

<img width="303" alt="Screen Shot 2020-08-21 at 2 23 14 PM" src="https://user-images.githubusercontent.com/22783/90931421-dd54d280-e3b9-11ea-961c-4c3c8a57993e.png">

Since we're discontinuing clusters this year, it can go away. If we bring it back in the future, might make sense to have it be a combo dropdown with tracks the way we do on the schedule page.

**Comment by Jessiewithani** [comment]
Went into admin and edit the active state of the listed options in clusters.
