### ISSUE TITLE
Add "virtual" copy to somewhere on the homepage

### ISSUE THREAD

**Issue by jayzes** [denverstartupweek/dsw-site#888]

**Comment by jayzes** [comment]
@Jessiewithani here's what I'm thinking for the moment - let's change the homepage header to read `DENVER STARTUP WEEK: VIRTUAL`: 
<img width="814" alt="Screen Shot 2020-09-02 at 1 22 52 PM" src="https://user-images.githubusercontent.com/22783/92027377-aff41700-ed1f-11ea-8ff9-2c91e2159ad3.png">

There may be a few more things we can do after we talk with Kelsey today (there's an updated logo, for example) but that'll head off the current questions about format.

**Comment by Jessiewithani** [comment]
alright! Sounds good I will get right on it.
